server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          app: bluesky-backend
          __path__: /opt/app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            error: error
            identifier: identifier
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
      - output:
          source: message
